declare const colors: {
    redD1: string;
    redL1: string;
    redL2: string;
    cyanD1: string;
    cyanL1: string;
    cyanL2: string;
    blueD1: string;
    blueL1: string;
    blueL2: string;
    pinkD1: string;
    pinkL1: string;
    pinkL2: string;
    greenD1: string;
    greenL1: string;
    greenL2: string;
    orangeD1: string;
    orangeL1: string;
    orangeL2: string;
    yellowD1: string;
    yellowL1: string;
    yellowL2: string;
    purpleD1: string;
    purpleL1: string;
    purpleL2: string;
    red: string;
    cyan: string;
    blue: string;
    pink: string;
    green: string;
    orange: string;
    yellow: string;
    purple: string;
    shades: {
        grey: string;
        greyD1: string;
        greyL1: string;
        greyL2: string;
        blue: string;
        blueD1: string;
        blueD2: string;
        pink: string;
        pinkL1: string;
    };
};
export default colors;
